{{- if .Values.enableDeployment | default false -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.default_name }}
  labels: 
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount | default "1" }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
    spec:
      {{- if .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.deployment.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.default_name }}
      securityContext:
        {{ toYaml .Values.deployment.securityContext }}
      containers:
        - name: {{ .Values.name | default ".Values.default_name" }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: {{ .Values.args }}
          ports:
            {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.envFrom }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          {{- end }}
          env:
            {{- toYaml .Values.container_env | nindent 12 }}
          command: {{ .Values.command }}
          securityContext:
            {{- toYaml  .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
      volumes:
        {{- toYaml .Values.deployment.volumes | nindent 8 }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.deployment.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
        {{ toYaml .Values.deployment.tolerations | indent 6 }}
      {{- end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
{{- end }}

