{{- if .Values.enableServiceAccount | default false -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.default_name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}
