name: "Helm package"

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#        with:
#          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - uses: actions/setup-python@v4
        with:
           python-version: '3.10'
      - run: pip install bump2version

      - name: Bump
        run: |
          git config --global user.email "mitkaua@gmail.com"
          git config --global user.name "FanscrmBot"
          bump2version patch
          new_version=$(cat VERSION)
          echo "New version $new_version"
          cat VERSION
          
      - name: Test
        run: |
          new_version=$(cat VERSION)
          echo test$new_version
#      - name: Helm install
#        env :
#          HELM_USER: ${{ secrets.HELM_USER }}
#          HELM_TOKEN: ${{ secrets.HELM_TOKEN }}
#        run: |
#          helm repo add crm-helms --username ${HELM_USER} --password ${HELM_TOKEN} "https://raw.githubusercontent.com/fanscrm-dev/infra/main/"
#          helm repo update
#          helm repo list
#          helm search repo crm-helms
          
#      - name: Update chart messaging-service
#        run: helm package basic-chart

#      - name: Update Index
#        run: |
#          git config --global user.email "maksiktosh@gmail.com"
#          git config --global user.name "maksiktosh"
#          helm repo index .
#          git add index.yaml *.tgz
#          git commit -m "Update chart index"
#          git push
