name: "Create cluster with terraform"

on:
  push:
    branches:
      - main
#    paths:
#      - 'crm-tf/**'

#env:
#  working-directory: cluster
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crm-tf/cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -la
      
      - name: 'Authenticate to AWS for spaces backend'
        id: 'auth'
#        uses: aws-actions/configure-aws-credentials@v2
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile digitalocean
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile digitalocean
          aws configure set aws-region: ${{ secrets.AWS_REGION }} --profile digitalocean
          export AWS_PROFILE=digitalocean
      
#      - name: Install doctl
#        uses: digitalocean/action-doctl@v2
#        with:
#          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        id: init
        run: |
          export AWS_PROFILE=digitalocean
          terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
#        continue-on-error: true
