name: "Build Windows Application"

on:
  push:
    branches:
      - windows

jobs:
  build-windows:
    runs-on:
      - windows-latest
    steps:
      
      - name: Clone Repo
        run: |
          mkdir backend-app\front
          cd backend-app
          dir ~\backend-app
